### ISSUE TITLE
Problematic pam-config

### ISSUE THREAD

**Issue by piersharding** [jeroennijhof/pam_script#7]
Hi -

did you ever see this launch pad bug ? https://bugs.launchpad.net/ubuntu/+source/libpam-script/+bug/1411225 .  I think this may still be a problem as I have just been bitten by the entries:
```
(account|auth|password) sufficient                      pam_script.so
```
being added to the common-* files leaving my Ubuntu instance open to a user with any password as was reported on launch pad.

I'm wondering if it would be better to omit this auto-configuration as a security precaution for others?

Thanks,
Piers Harding.

**Comment by jeroennijhof** [comment]
No I didn't thanks for pointing out!

**Comment by jeroennijhof** [comment]
Actually I'm removing the debian directory out of the source tree since it is maintained by a debian developer now. I have contacted him to replace all sufficient with optional so it keeps current pam stack intact.

**Comment by piersharding** [comment]
Thanks - can you point me to the debian maintained repository?

Cheers,
Piers Harding.

**Comment by jeroennijhof** [comment]
You can find it at debian.org:
https://packages.debian.org/sid/libpam-script
